[package]
name = "compiler"
version = "0.6.1"
authors = ["Andrea Fioraldi <andreafioraldi@gmail.com>", "Dominik Maier <domenukk@gmail.com>"]
edition = "2021"

[dependencies]
libafl_cc = { path = "../../../libafl_cc/" }
